"""Executable multi-step paper retrieval for the Shenzhi KG backend.

Stage2 selects one abstract operation skill at each decision.  This module owns
the deterministic argument binding and execution semantics, so the model never
has to invent author names, keyword IDs, or paper IDs.  The same executor is
used for weak-bootstrap trajectory generation and online HTTP inference.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
import json
from contextlib import nullcontext
import importlib
from pathlib import Path
import sys
import threading
from typing import Any, Iterable, Protocol

try:
    from .paper_search import CandidateHit, SearchFilters, SearchResult
    from .retrieval_pipeline import HybridPaperSearch, reciprocal_rank_fusion
    from .query_rewrite import contains_cjk
    from .graph_query import infer_graph_query_plan
except ImportError:
    from paper_search import CandidateHit, SearchFilters, SearchResult
    from retrieval_pipeline import HybridPaperSearch, reciprocal_rank_fusion
    from query_rewrite import contains_cjk
    from graph_query import infer_graph_query_plan


SEARCH_PAPERS = "SEARCH_PAPERS"
EXPAND_AUTHORS = "EXPAND_AUTHORS"
EXPAND_KEYWORDS = "EXPAND_KEYWORDS"
EXPAND_SUBJECTS = "EXPAND_SUBJECTS"
EXPAND_VENUE_YEAR = "EXPAND_VENUE_YEAR"
RERANK_RESULTS = "RERANK_RESULTS"
STOP = "STOP"
ACTION_SLOT_COUNT = 128
SLOTTED_ACTIONS = (
    EXPAND_AUTHORS,
    EXPAND_KEYWORDS,
    EXPAND_SUBJECTS,
    EXPAND_VENUE_YEAR,
)

ACTION_ORDER = (
    SEARCH_PAPERS,
    EXPAND_AUTHORS,
    EXPAND_KEYWORDS,
    EXPAND_SUBJECTS,
    EXPAND_VENUE_YEAR,
    RERANK_RESULTS,
    STOP,
)

BASE_ACTION_SKILLS: tuple[dict[str, Any], ...] = (
    {
        "skill_id": SEARCH_PAPERS,
        "name": "Search papers",
        "description": "Recall papers from the original user query with BM25 and, when configured, the paper Stage0 dense retriever.",
        "body": "Use this first when no candidate papers have been retrieved. It executes lexical and optional dense paper recall with the current metadata filters.",
    },
    {
        "skill_id": EXPAND_AUTHORS,
        "name": "Expand by authors",
        "description": "Follow authors from the current top papers and retrieve other papers by the same authors.",
        "body": "Use when the user asks for related work by the same researchers or when author evidence can broaden a narrow result set. Arguments are bound from current paper metadata.",
    },
    {
        "skill_id": EXPAND_KEYWORDS,
        "name": "Expand by keywords",
        "description": "Follow exact keyword nodes from current papers and retrieve papers sharing those keywords.",
        "body": "Use to broaden a topical search after initial recall. Keyword values are taken from returned papers rather than generated by the router.",
    },
    {
        "skill_id": EXPAND_SUBJECTS,
        "name": "Expand by subjects",
        "description": "Follow subject-category nodes from current papers and retrieve papers in the same subject areas.",
        "body": "Use for broader field or subfield exploration after initial paper recall. Subject values are bound from current results.",
    },
    {
        "skill_id": EXPAND_VENUE_YEAR,
        "name": "Expand by venue and year",
        "description": "Retrieve papers from the same venues and nearby publication years as the current results.",
        "body": "Use for conference/year neighborhood exploration or recent nearby work. The executor binds venue-year pairs from current papers.",
    },
    {
        "skill_id": RERANK_RESULTS,
        "name": "Rerank accumulated results",
        "description": "Use the configured SkillRouter reranker to reorder the bounded accumulated candidate set for the original query.",
        "body": "Use after recall or expansion when a neural reranker is configured and final precision should be improved.",
    },
    {
        "skill_id": STOP,
        "name": "Stop retrieval",
        "description": "Finish the multi-step search and return the current ranked papers.",
        "body": "Use when the result set is sufficient, no useful operation remains, or the maximum step budget is reached.",
    },
)


def action_skill_id(action: str, slot_index: int | None = None) -> str:
    resolved = str(action).strip()
    if resolved not in SLOTTED_ACTIONS:
        if slot_index is not None:
            raise ValueError(f"non-slotted action cannot carry a slot: {resolved}")
        return resolved
    if slot_index is None or not 0 <= int(slot_index) < ACTION_SLOT_COUNT:
        raise ValueError(f"slotted action requires slot 0..{ACTION_SLOT_COUNT - 1}")
    return f"{resolved}@{int(slot_index):03d}"


def parse_action_skill(skill_id: str) -> tuple[str, int | None]:
    raw = str(skill_id).strip()
    head, marker, tail = raw.partition("@")
    if not marker:
        if head in ACTION_ORDER:
            return head, None
        raise ValueError(f"unknown retrieval action skill: {raw}")
    if head not in SLOTTED_ACTIONS or not tail.isdigit():
        raise ValueError(f"invalid retrieval action skill: {raw}")
    slot = int(tail)
    if not 0 <= slot < ACTION_SLOT_COUNT:
        raise ValueError(f"retrieval action slot is out of range: {raw}")
    return head, slot


def _action_skills() -> tuple[dict[str, Any], ...]:
    by_action = {str(row["skill_id"]): row for row in BASE_ACTION_SKILLS}
    output: list[dict[str, Any]] = []
    for action in (SEARCH_PAPERS, RERANK_RESULTS, STOP):
        output.append(dict(by_action[action]))
    for action in SLOTTED_ACTIONS:
        base = by_action[action]
        for slot in range(ACTION_SLOT_COUNT):
            copied = dict(base)
            copied["skill_id"] = action_skill_id(action, slot)
            copied["name"] = f"{base['name']} — slot {slot + 1}"
            copied["description"] = (
                f"{base['description']} Use deterministic current-result slot {slot + 1}."
            )
            copied["body"] = (
                f"{base['body']} The executor binds slot {slot + 1}; no parameter is generated by the model."
            )
            copied["base_action"] = action
            copied["slot_index"] = slot
            output.append(copied)
    return tuple(output)


ACTION_SKILLS = _action_skills()


class ActionPolicy(Protocol):
    def choose_action(
        self,
        state: "MultiStepSearchState",
        legal_actions: list[str],
    ) -> tuple[str, dict[str, Any]]: ...

    def observe(
        self,
        state_text_before: str,
        event: "ActionEvent",
    ) -> None: ...


@dataclass
class ActionEvent:
    step_index: int
    skill_id: str
    action: str
    action_text: str
    state_text_before: str
    legal_actions: list[str]
    status: str
    result_text: str
    result_ids: list[str] = field(default_factory=list)
    new_result_ids: list[str] = field(default_factory=list)
    bound_values: list[str] = field(default_factory=list)
    policy: dict[str, Any] = field(default_factory=dict)


@dataclass
class MultiStepSearchState:
    query: str
    query_variants: dict[str, Any] = field(default_factory=dict)
    filters: SearchFilters = field(default_factory=SearchFilters)
    max_steps: int = 6
    candidate_ids: list[str] = field(default_factory=list)
    score_by_id: dict[str, float] = field(default_factory=dict)
    source_scores_by_id: dict[str, dict[str, float]] = field(default_factory=dict)
    events: list[ActionEvent] = field(default_factory=list)
    stopped: bool = False
    stop_reason: str = ""
    failures: list[str] = field(default_factory=list)
    relation_plan: list[str] = field(default_factory=list)

    @property
    def step(self) -> int:
        return len(self.events)

    @property
    def executed_actions(self) -> list[str]:
        return [event.action for event in self.events]

    @property
    def executed_skill_ids(self) -> list[str]:
        return [event.skill_id for event in self.events]

    def current_state_text(self) -> str:
        filters = asdict(self.filters)
        active_filters = {
            key: value
            for key, value in filters.items()
            if value not in (None, [], "")
        }
        observation = (
            f"retrieval_phase={'initial' if not self.events else 'followup'}; "
            f"remaining_step_budget={max(0, int(self.max_steps) - self.step)}; "
            f"filters={json.dumps(active_filters, ensure_ascii=False, sort_keys=True)}"
        )
        return "\n".join(
            (
                f"goal: {self.query}",
                "task: retrieve relevant papers through executable search operations",
                f"observation: {observation}",
            )
        )


class PlannedActionPolicy:
    """Deterministic policy for replayable bootstrap workflows and tests."""

    def __init__(self, actions: Iterable[str]) -> None:
        self.actions = [str(action) for action in actions]
        self.position = 0

    def choose_action(
        self,
        state: MultiStepSearchState,
        legal_actions: list[str],
    ) -> tuple[str, dict[str, Any]]:
        del state
        if self.position >= len(self.actions):
            action = STOP
        else:
            action = self.actions[self.position]
            self.position += 1
        if action not in legal_actions and action in SLOTTED_ACTIONS:
            action = next(
                (candidate for candidate in legal_actions if parse_action_skill(candidate)[0] == action),
                action,
            )
        if action not in legal_actions:
            raise ValueError(
                f"planned action is not legal at this decision: {action}; "
                f"legal={legal_actions}"
            )
        return action, {"method": "planned_replay_v1", "position": self.position - 1}

    def observe(self, state_text_before: str, event: ActionEvent) -> None:
        del state_text_before, event


class RuleActionPolicy:
    """Fail-safe policy used when a Stage2 release is not configured."""

    _intent = {
        EXPAND_AUTHORS: ("author", "authors", "researcher", "same team", "作者", "学者", "团队"),
        EXPAND_KEYWORDS: ("keyword", "topic", "related topic", "关键词", "主题词", "相关主题"),
        EXPAND_SUBJECTS: ("subject", "field", "area", "方向", "领域", "学科"),
        EXPAND_VENUE_YEAR: ("conference", "venue", "recent", "year", "会议", "近年", "年份", "最新"),
        RERANK_RESULTS: ("best", "most relevant", "rank", "最相关", "排序", "最好"),
    }

    def choose_action(
        self,
        state: MultiStepSearchState,
        legal_actions: list[str],
    ) -> tuple[str, dict[str, Any]]:
        if SEARCH_PAPERS in legal_actions:
            return SEARCH_PAPERS, {"method": "rule_fallback_v1", "reason": "no_candidates"}
        lowered = state.query.casefold()
        legal_by_base: dict[str, list[str]] = {}
        for skill_id in legal_actions:
            base, _slot = parse_action_skill(skill_id)
            legal_by_base.setdefault(base, []).append(skill_id)
        # For explicit multi-relation requests, preserve the user's relation
        # order. Hard metadata filters have already been applied by SEARCH and
        # are re-applied after every expansion; this policy only chooses the
        # next graph operation.
        relation_to_action = {
            "authors": EXPAND_AUTHORS,
            "keywords": EXPAND_KEYWORDS,
            "subjects": EXPAND_SUBJECTS,
            "venue_year": EXPAND_VENUE_YEAR,
        }
        executed_bases = set(state.executed_actions)
        for relation in state.relation_plan:
            action = relation_to_action.get(relation)
            if action in legal_by_base and action not in executed_bases:
                return legal_by_base[action][0], {
                    "method": "rule_fallback_v2_hybrid",
                    "reason": "planned_relation_order",
                    "relation": relation,
                }
        if state.relation_plan:
            # The explicit relation plan is authoritative. Once its requested
            # steps are exhausted (or no legal value exists), do not fall back
            # to repeatedly expanding the first matching intent phrase.
            if RERANK_RESULTS in legal_by_base:
                return RERANK_RESULTS, {
                    "method": "rule_fallback_v2_hybrid",
                    "reason": "planned_relations_complete",
                }
            return STOP, {
                "method": "rule_fallback_v2_hybrid",
                "reason": "planned_relations_complete",
            }
        for action in ACTION_ORDER:
            if action not in legal_by_base or action in {SEARCH_PAPERS, STOP}:
                continue
            if any(token.casefold() in lowered for token in self._intent.get(action, ())):
                return legal_by_base[action][0], {"method": "rule_fallback_v1", "reason": "query_intent"}
        if RERANK_RESULTS in legal_actions:
            return RERANK_RESULTS, {"method": "rule_fallback_v1", "reason": "final_precision"}
        return STOP, {"method": "rule_fallback_v1", "reason": "no_requested_expansion"}

    def observe(self, state_text_before: str, event: ActionEvent) -> None:
        del state_text_before, event


class Stage2ActionPolicy:
    """CLSTR Stage2 policy with a deterministic rule fallback.

    The model only chooses an abstract action skill from the executor-provided
    legal set.  Concrete authors, keywords, subjects and venue/year values are
    still bound by :class:`MultiStepPaperSearch`, so model output cannot invent
    identifiers.  A fresh recurrent session is created for every policy
    instance (and therefore every HTTP request).
    """

    def __init__(
        self,
        *,
        checkpoint_path: str,
        skills_path: str,
        clstr_source: str,
        device: str = "cuda",
        route_mode: str = "adaptive",
        coarse_k: int = 500,
        dynamic_extra_k: int = 64,
        fallback: ActionPolicy | None = None,
    ) -> None:
        self.checkpoint_path = str(checkpoint_path)
        self.skills_path = str(skills_path)
        self.clstr_source = str(clstr_source)
        self.device_name = str(device)
        self.route_mode = str(route_mode or "adaptive")
        self.coarse_k = int(coarse_k)
        self.dynamic_extra_k = int(dynamic_extra_k)
        self.fallback = fallback or RuleActionPolicy()
        self._load_error: str | None = None
        self._selector: Any | None = None
        self._session: Any | None = None
        self._load_model()

    @property
    def enabled(self) -> bool:
        return self._session is not None

    @property
    def load_error(self) -> str | None:
        return self._load_error

    def new_episode(self) -> "Stage2ActionPolicy":
        """Return a request-local policy sharing the loaded frozen model."""
        episode = object.__new__(Stage2ActionPolicy)
        episode.checkpoint_path = self.checkpoint_path
        episode.skills_path = self.skills_path
        episode.clstr_source = self.clstr_source
        episode.device_name = self.device_name
        episode.route_mode = self.route_mode
        episode.coarse_k = self.coarse_k
        episode.dynamic_extra_k = self.dynamic_extra_k
        episode.fallback = RuleActionPolicy()
        episode._load_error = self._load_error
        episode._selector = self._selector
        episode._session = (
            None
            if self._selector is None
            else self._session.__class__(self._selector)
        )
        return episode

    def _load_model(self) -> None:
        try:
            checkpoint = Path(self.checkpoint_path)
            skills = Path(self.skills_path)
            source_path = Path(self.clstr_source)
            if not checkpoint.is_file():
                raise FileNotFoundError(f"Stage2 checkpoint not found: {checkpoint}")
            if not skills.is_file():
                raise FileNotFoundError(f"Stage2 skills not found: {skills}")
            if not source_path.is_dir():
                raise FileNotFoundError(f"Stage2 CLSTR source not found: {source_path}")
            source = self.clstr_source
            if source and source not in sys.path:
                sys.path.insert(0, source)
            torch = importlib.import_module("torch")
            vnext_eval = importlib.import_module("clstr.vnext_eval")
            online = importlib.import_module("clstr.vnext_online_selector")
            device = torch.device(self.device_name)
            if device.type == "cuda" and not torch.cuda.is_available():
                raise RuntimeError("CUDA is unavailable")
            model, skills, skill_id_to_idx, report = (
                vnext_eval.load_vnext_stage2_for_evaluation(
                    checkpoint_path=self.checkpoint_path,
                    training_skills_path=self.skills_path,
                    benchmark_skills=[],
                    device=device,
                )
            )

            # VNextOnlineSession only needs this small selector interface.  We
            # intentionally avoid VNextOnlineSelector here because that class
            # requires a matched-release selection file, while this backend
            # accepts an explicitly supplied project checkpoint.
            class _SelectorAdapter:
                pass

            selector = _SelectorAdapter()
            selector.model = model
            selector.skills = skills
            selector.skill_id_to_idx = dict(skill_id_to_idx)
            selector.skill_index = selector.skill_id_to_idx
            selector.skill_ids = [str(row.get("skill_id") or row.get("id") or "") for row in skills]
            selector.device = device
            selector.belief_top_k = None
            selector.coarse_k = max(1, int(self.coarse_k))
            selector.dynamic_extra_k = max(1, int(self.dynamic_extra_k))
            selector._model_lock = threading.RLock()

            def _autocast():
                if device.type == "cuda":
                    return torch.autocast(device_type="cuda", dtype=torch.bfloat16)
                return nullcontext()

            selector._autocast = _autocast
            selector.checkpoint_binding = {
                "checkpoint_path": self.checkpoint_path,
                "skills_path": self.skills_path,
                "load_report": report,
                "protocol": "native_factual_stage2_recurrent_v1",
            }
            self._selector = selector
            self._session = online.VNextOnlineSession(selector)
        except Exception as exc:  # model is optional; rules remain available
            self._load_error = f"{type(exc).__name__}: {exc}"
            self._selector = None
            self._session = None

    def choose_action(
        self,
        state: MultiStepSearchState,
        legal_actions: list[str],
    ) -> tuple[str, dict[str, Any]]:
        if self._session is None:
            action, metadata = self.fallback.choose_action(state, legal_actions)
            metadata = {**metadata, "stage2_enabled": False, "stage2_load_error": self._load_error}
            return action, metadata
        try:
            ranked = self._session.select(
                state.current_state_text(),
                candidate_skill_ids=legal_actions,
                top_k=1,
                coarse_k=self.coarse_k,
                dynamic_extra_k=self.dynamic_extra_k,
                route_mode=self.route_mode,
            )
            if not ranked:
                raise RuntimeError("Stage2 returned no legal action")
            selected = str(ranked[0]["skill_id"])
            if selected not in legal_actions:
                raise RuntimeError(f"Stage2 selected an illegal action: {selected}")
            return selected, {
                "method": "clstr_vnext_stage2_native",
                "stage2_enabled": True,
                "route_mode": self.route_mode,
                "ranked": ranked[:3],
            }
        except Exception as exc:
            action, metadata = self.fallback.choose_action(state, legal_actions)
            return action, {
                **metadata,
                "stage2_enabled": False,
                "stage2_runtime_fallback": f"{type(exc).__name__}: {exc}",
            }

    def observe(self, state_text_before: str, event: ActionEvent) -> None:
        if self._session is None:
            self.fallback.observe(state_text_before, event)
            return
        try:
            self._session.observe(
                state_text_before=state_text_before,
                skill_id=event.skill_id,
                action_text=event.action_text,
                result_text=event.result_text,
            )
        except Exception:
            # Memory update failures should not make retrieval unavailable.
            self.fallback.observe(state_text_before, event)


class MultiStepPaperSearch:
    def __init__(
        self,
        engine: HybridPaperSearch,
        *,
        expansion_seed_k: int = 12,
        candidate_limit: int = 100,
    ) -> None:
        self.engine = engine
        self.index = engine.lexical_index
        self.expansion_seed_k = max(1, int(expansion_seed_k))
        self.candidate_limit = max(10, min(int(candidate_limit), 100))

    @staticmethod
    def _rerank_query(state: MultiStepSearchState) -> str:
        """Return an English reranker input, or empty for browse-only queries."""

        variants = state.query_variants
        translated = str(variants.get("translated_query") or "").strip()
        if translated and not contains_cjk(translated):
            return translated
        semantic = str(variants.get("semantic_query") or "").strip()
        if semantic and not contains_cjk(semantic):
            return semantic
        if not variants and not contains_cjk(state.query):
            return state.query
        return ""

    def _apply_graph_filter(self, state: MultiStepSearchState) -> None:
        """Apply configured Neo4j constraints to the accumulated result set."""
        graph = getattr(self.engine, "graph_filter", None)
        if graph is None or not state.candidate_ids:
            return
        try:
            state.candidate_ids = list(
                graph.filter_candidate_ids(state.candidate_ids, filters=state.filters)
            )
        except Exception as exc:
            state.failures.append(f"graph_filter:{type(exc).__name__}")
            # Keep the accumulated candidates.  The local SQLite fetch still
            # applies the same scalar/list filters when results are hydrated.

    def _graph_expansion(
        self,
        seed_ids: list[str],
        *,
        relation: str,
        slot_index: int | None,
        state: MultiStepSearchState | None = None,
    ) -> tuple[list[CandidateHit], list[str]] | None:
        graph = getattr(self.engine, "graph_filter", None)
        expand = getattr(graph, "expand_from_papers", None)
        if not callable(expand):
            return None
        try:
            rows, values = expand(
                seed_ids,
                relation=relation,
                value_limit=ACTION_SLOT_COUNT,
                paper_limit=self.candidate_limit,
                slot_index=slot_index,
            )
        except Exception as exc:
            if state is not None:
                state.failures.append(f"expand_{relation}_neo4j:{type(exc).__name__}")
            return None
        seed_set = set(seed_ids)
        counts: dict[str, int] = {}
        for _value, paper_ids in rows:
            for paper_id in paper_ids:
                if paper_id not in seed_set:
                    counts[paper_id] = counts.get(paper_id, 0) + 1
        ordered = sorted(counts, key=lambda paper_id: (-counts[paper_id], paper_id))[: self.candidate_limit]
        return [
            CandidateHit(
                paper_id=paper_id,
                score=float(counts[paper_id]),
                rank=index + 1,
                source=f"expand_{relation}_neo4j",
            )
            for index, paper_id in enumerate(ordered)
        ], values

    def _relation_values(
        self,
        seed_ids: list[str],
        *,
        relation: str,
        state: MultiStepSearchState | None = None,
    ) -> list[str]:
        graph = getattr(self.engine, "graph_filter", None)
        expand = getattr(graph, "expand_from_papers", None)
        if callable(expand):
            try:
                _rows, values = expand(
                    seed_ids,
                    relation=relation,
                    value_limit=ACTION_SLOT_COUNT,
                    paper_limit=1,
                )
                return values
            except Exception as exc:
                if state is not None:
                    state.failures.append(f"values_{relation}_neo4j:{type(exc).__name__}")
        return self.index.related_values(
            seed_ids,
            relation=relation,
            limit=ACTION_SLOT_COUNT,
        )

    def legal_actions(self, state: MultiStepSearchState) -> list[str]:
        if state.stopped:
            return []
        if state.step >= int(state.max_steps):
            return [STOP]
        executed = set(state.executed_skill_ids)
        if not state.candidate_ids:
            return [SEARCH_PAPERS]
        legal: list[str] = []
        seeds = state.candidate_ids[: self.expansion_seed_k]
        for action, relation in (
            (EXPAND_AUTHORS, "authors"),
            (EXPAND_KEYWORDS, "keywords"),
            (EXPAND_SUBJECTS, "subjects"),
        ):
            values = self._relation_values(seeds, relation=relation, state=state)
            legal.extend(
                skill_id
                for slot in range(len(values))
                if (skill_id := action_skill_id(action, slot)) not in executed
            )
        graph = getattr(self.engine, "graph_filter", None)
        if callable(getattr(graph, "expand_from_papers", None)):
            try:
                _rows, values = graph.expand_from_papers(
                    seeds,
                    relation="venue_year",
                    value_limit=ACTION_SLOT_COUNT,
                    paper_limit=1,
                )
            except Exception as exc:
                state.failures.append(f"values_venue_year_neo4j:{type(exc).__name__}")
                _hits, values = self.index.expand_venue_year(
                    seeds, limit=1, value_limit=ACTION_SLOT_COUNT
                )
        else:
            _hits, values = self.index.expand_venue_year(
                seeds, limit=1, value_limit=ACTION_SLOT_COUNT
            )
        legal.extend(
            skill_id
            for slot in range(len(values))
            if (skill_id := action_skill_id(EXPAND_VENUE_YEAR, slot)) not in executed
        )
        if (
            RERANK_RESULTS not in executed
            and self.engine.reranker is not None
            and state.candidate_ids
            and self._rerank_query(state)
        ):
            legal.append(RERANK_RESULTS)
        legal.append(STOP)
        order = {action: index for index, action in enumerate(ACTION_ORDER)}
        return sorted(
            dict.fromkeys(legal),
            key=lambda skill_id: (
                order[parse_action_skill(skill_id)[0]],
                -1 if parse_action_skill(skill_id)[1] is None else parse_action_skill(skill_id)[1],
            ),
        )

    @staticmethod
    def _summary(
        action: str,
        *,
        result_ids: list[str],
        new_ids: list[str],
        values: list[str],
        status: str,
    ) -> str:
        return json.dumps(
            {
                "action": action,
                "status": status,
                "candidate_count": len(result_ids),
                "new_candidate_count": len(new_ids),
                "bound_values": values[:12],
                "top_paper_ids": result_ids[:10],
            },
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )

    def _hydrate(self, state: MultiStepSearchState) -> list[SearchResult]:
        return self.index.fetch_results(
            state.candidate_ids,
            filters=state.filters,
            top_k=self.candidate_limit,
            score_by_id=state.score_by_id,
            source_scores_by_id=state.source_scores_by_id,
            retrieval_mode="multistep",
        )

    def _merge_expansion(
        self,
        state: MultiStepSearchState,
        hits: list[CandidateHit],
        *,
        source: str,
    ) -> list[str]:
        previous = list(state.candidate_ids)
        current_hits = [
            CandidateHit(
                paper_id=paper_id,
                score=float(state.score_by_id.get(paper_id, 0.0)),
                rank=rank,
                source="accumulated",
            )
            for rank, paper_id in enumerate(previous, start=1)
        ]
        ordered, scores, components = reciprocal_rank_fusion(
            {"accumulated": current_hits, source: hits},
            rank_constant=30,
        )
        state.candidate_ids = ordered[: self.candidate_limit]
        state.score_by_id = {
            paper_id: float(scores[paper_id]) for paper_id in state.candidate_ids
        }
        state.source_scores_by_id = {
            paper_id: {
                **state.source_scores_by_id.get(paper_id, {}),
                **components.get(paper_id, {}),
            }
            for paper_id in state.candidate_ids
        }
        previous_set = set(previous)
        return [paper_id for paper_id in state.candidate_ids if paper_id not in previous_set]

    def execute_action(
        self,
        state: MultiStepSearchState,
        action: str,
        *,
        legal_actions: list[str] | None = None,
        policy_metadata: dict[str, Any] | None = None,
    ) -> ActionEvent:
        legal = legal_actions or self.legal_actions(state)
        if action not in legal and action in SLOTTED_ACTIONS:
            action = next(
                (candidate for candidate in legal if parse_action_skill(candidate)[0] == action),
                action,
            )
        if action not in legal:
            raise ValueError(f"illegal multi-step action: {action}; legal={legal}")
        skill_id = action
        action, slot_index = parse_action_skill(skill_id)
        before = state.current_state_text()
        old_ids = list(state.candidate_ids)
        values: list[str] = []
        status = "ok"
        action_text = action
        try:
            if action == SEARCH_PAPERS:
                results, _search_state = self.engine.search(
                    state.query,
                    filters=state.filters,
                    top_k=self.candidate_limit,
                    apply_reranker=False,
                    query_variants=state.query_variants,
                )
                state.candidate_ids = [row.paper_id for row in results]
                state.score_by_id = {row.paper_id: float(row.score) for row in results}
                state.source_scores_by_id = {
                    row.paper_id: dict(row.source_scores) for row in results
                }
                self._apply_graph_filter(state)
                new_ids = list(state.candidate_ids)
                action_text = f"SEARCH_PAPERS(query={state.query!r})"
            elif action in {EXPAND_AUTHORS, EXPAND_KEYWORDS, EXPAND_SUBJECTS}:
                relation = {
                    EXPAND_AUTHORS: "authors",
                    EXPAND_KEYWORDS: "keywords",
                    EXPAND_SUBJECTS: "subjects",
                }[action]
                graph_result = self._graph_expansion(
                    state.candidate_ids[: self.expansion_seed_k],
                    relation=relation,
                    slot_index=slot_index,
                    state=state,
                )
                if graph_result is None:
                    hits, values = self.index.expand_related(
                        state.candidate_ids[: self.expansion_seed_k],
                        relation=relation,
                        limit=self.candidate_limit,
                        slot_index=slot_index,
                    )
                else:
                    hits, values = graph_result
                new_ids = self._merge_expansion(
                    state, hits, source=f"expand_{relation}"
                )
                self._apply_graph_filter(state)
                new_ids = [paper_id for paper_id in state.candidate_ids if paper_id not in set(old_ids)]
                action_text = f"{action}(values={values[:12]!r})"
            elif action == EXPAND_VENUE_YEAR:
                graph_result = self._graph_expansion(
                    state.candidate_ids[: self.expansion_seed_k],
                    relation="venue_year",
                    slot_index=slot_index,
                    state=state,
                )
                if graph_result is None:
                    hits, values = self.index.expand_venue_year(
                        state.candidate_ids[: self.expansion_seed_k],
                        limit=self.candidate_limit,
                        value_limit=ACTION_SLOT_COUNT,
                        slot_index=slot_index,
                    )
                else:
                    hits, values = graph_result
                new_ids = self._merge_expansion(
                    state, hits, source="expand_venue_year"
                )
                self._apply_graph_filter(state)
                new_ids = [paper_id for paper_id in state.candidate_ids if paper_id not in set(old_ids)]
                action_text = f"EXPAND_VENUE_YEAR(values={values[:12]!r})"
            elif action == RERANK_RESULTS:
                if self.engine.reranker is None:
                    raise RuntimeError("RERANK_RESULTS requires a configured reranker")
                candidates = self._hydrate(state)[: self.engine.rerank_k]
                rerank_query = self._rerank_query(state)
                if not rerank_query:
                    raise RuntimeError("RERANK_RESULTS requires an English query")
                ranked = self.engine.reranker.rerank(rerank_query, candidates)
                ranked_ids = [paper_id for paper_id, _score in ranked]
                tail = [item for item in state.candidate_ids if item not in set(ranked_ids)]
                state.candidate_ids = [*ranked_ids, *tail][: self.candidate_limit]
                for paper_id, score in ranked:
                    state.score_by_id[paper_id] = float(score)
                    state.source_scores_by_id.setdefault(paper_id, {})[
                        "reranker"
                    ] = float(score)
                new_ids = []
                action_text = f"RERANK_RESULTS(candidate_count={len(candidates)})"
            elif action == STOP:
                state.stopped = True
                state.stop_reason = (
                    "max_steps" if state.step >= int(state.max_steps) - 1 else "policy_stop"
                )
                new_ids = []
                action_text = f"STOP(reason={state.stop_reason})"
            else:  # pragma: no cover - ACTION_ORDER and legal_actions prevent this
                raise ValueError(f"unknown multi-step action: {action}")
        except Exception as exc:
            status = "error"
            state.failures.append(f"{action}:{type(exc).__name__}")
            new_ids = []
            if action != STOP:
                state.stopped = True
                state.stop_reason = "action_error"
            result_text = json.dumps(
                {"action": action, "status": status, "error": type(exc).__name__},
                sort_keys=True,
            )
        else:
            result_text = self._summary(
                action,
                result_ids=state.candidate_ids,
                new_ids=new_ids,
                values=values,
                status=status,
            )
        event = ActionEvent(
            step_index=state.step,
            skill_id=skill_id,
            action=action,
            action_text=action_text,
            state_text_before=before,
            legal_actions=list(legal),
            status=status,
            result_text=result_text,
            result_ids=list(state.candidate_ids),
            new_result_ids=list(new_ids),
            bound_values=list(values),
            policy=dict(policy_metadata or {}),
        )
        state.events.append(event)
        if action == STOP:
            state.stopped = True
        if old_ids and action != STOP and not state.candidate_ids:
            state.failures.append(f"{action}:empty_candidates")
        return event

    def run(
        self,
        query: str,
        *,
        policy: ActionPolicy | None = None,
        filters: SearchFilters | None = None,
        top_k: int = 10,
        max_steps: int = 6,
        query_variants: dict[str, Any] | None = None,
    ) -> tuple[list[SearchResult], MultiStepSearchState]:
        policy = policy or RuleActionPolicy()
        state = MultiStepSearchState(
            query=str(query).strip(),
            query_variants=dict(query_variants or {}),
            filters=filters or SearchFilters(),
            max_steps=max(2, min(int(max_steps), 16)),
            relation_plan=list(
                infer_graph_query_plan(query, filters).expansion_relations
            ),
        )
        if not state.query:
            raise ValueError("multi-step search requires a nonempty query")
        while not state.stopped:
            legal = self.legal_actions(state)
            action, metadata = policy.choose_action(state, legal)
            before = state.current_state_text()
            event = self.execute_action(
                state,
                action,
                legal_actions=legal,
                policy_metadata=metadata,
            )
            policy.observe(before, event)
            if state.step >= state.max_steps and not state.stopped:
                stop_legal = self.legal_actions(state)
                stop = self.execute_action(
                    state,
                    STOP,
                    legal_actions=stop_legal,
                    policy_metadata={"method": "executor_guard_v1"},
                )
                policy.observe(state.current_state_text(), stop)
        results = self.index.fetch_results(
            state.candidate_ids,
            filters=state.filters,
            top_k=max(1, min(int(top_k), 100)),
            score_by_id=state.score_by_id,
            source_scores_by_id=state.source_scores_by_id,
            retrieval_mode="multistep",
        )
        for rank, result in enumerate(results, start=1):
            result.rank = rank
        return results, state


def multistep_payload(
    results: list[SearchResult],
    state: MultiStepSearchState,
) -> dict[str, Any]:
    return {
        "results": [asdict(result) for result in results],
        "state": {
            **asdict(state),
            "filters": asdict(state.filters),
        },
    }
