"""Align an A-layer addition directory to an existing Neo4j CSV baseline.

IDs generated by different graph exports are not semantic identities.  This
step maps exact arXiv/DOI papers and normalized Author/Keyword/Venue/Subject/
Year names to baseline IDs before the additive merge.  Title-only Paper
matches are quarantined by default because title equality alone is not strong
enough for an online graph update.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
from collections import Counter, defaultdict
from pathlib import Path
import re
import shutil
import tempfile
from typing import Any, Mapping, Sequence
import unicodedata
import zipfile


NODE_FILES = ("papers", "authors", "venues", "keywords", "subjects", "years")
RELATION_FILES = ("authored_by", "published_in", "published_year", "has_keyword", "has_subject", "cites")


def norm(value: Any) -> str:
    return " ".join(unicodedata.normalize("NFKC", str(value or "")).casefold().split())


def arxiv(value: Any) -> str:
    value = norm(value)
    value = re.sub(r"^https?://arxiv\.org/(?:abs|pdf)/", "", value).removesuffix(".pdf")
    return re.sub(r"v\d+$", "", value)


def doi(value: Any) -> str:
    value = norm(value)
    return value.removeprefix("https://doi.org/").removeprefix("doi:")


def suspect_modern_arxiv(value: Any) -> bool:
    """Flag the known 2026 four-digit sequence truncation pattern."""
    value = norm(value)
    value = re.sub(r"^https?://arxiv\.org/(?:abs|pdf)/", "", value).removesuffix(".pdf")
    return bool(re.fullmatch(r"26\d{2}\.\d{4}(?:v\d+)?", value))


def _member(archive: zipfile.ZipFile, suffix: str) -> str:
    matches = [name for name in archive.namelist() if name.endswith(suffix)]
    if len(matches) != 1:
        raise ValueError(f"expected one baseline member {suffix!r}, found {matches}")
    return matches[0]


def _read_zip_csv(archive: zipfile.ZipFile, member: str) -> tuple[list[str], list[list[str]]]:
    with archive.open(member) as raw:
        text = io.TextIOWrapper(raw, encoding="utf-8-sig", newline="")
        reader = csv.reader(text)
        header = next(reader, None)
        if not header:
            raise ValueError(f"empty CSV member: {member}")
        return [str(field).lstrip("\ufeff") for field in header], list(reader)


def _read_csv(path: Path) -> tuple[list[str], list[list[str]]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.reader(handle)
        header = next(reader, None)
        if not header:
            raise ValueError(f"empty CSV: {path}")
        rows = [row for row in reader if any(str(value).strip() for value in row)]
        return [str(field).lstrip("\ufeff") for field in header], rows


def _write_csv(path: Path, header: Sequence[str], rows: Sequence[Sequence[str]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(header)
        writer.writerows(rows)


def _id_index(header: Sequence[str]) -> int:
    for index, field in enumerate(header):
        if ":ID(" in field:
            return index
    raise ValueError(f"CSV has no ID column: {header}")


def _base_indexes(base_zip: Path) -> tuple[dict[str, dict[str, list[str]]], dict[str, list[str]]]:
    maps: dict[str, dict[str, list[str]]] = {stem: defaultdict(list) for stem in NODE_FILES}
    headers: dict[str, list[str]] = {}
    with zipfile.ZipFile(base_zip) as archive:
        for stem in NODE_FILES:
            header, rows = _read_zip_csv(archive, _member(archive, f"/paper_kg/{stem}.csv"))
            headers[stem] = header
            identity_columns = [i for i, field in enumerate(header) if ":ID(" in field]
            id_col = identity_columns[0]
            if stem == "papers":
                fields = {field: i for i, field in enumerate(header)}
                for row in rows:
                    pid = row[id_col]
                    for key in (arxiv(row[fields.get("arxiv_id", -1)] if "arxiv_id" in fields else ""), doi(row[fields.get("doi", -1)] if "doi" in fields else ""), norm(row[fields.get("title", -1)] if "title" in fields else "")):
                        if key:
                            maps[stem][key].append(pid)
            elif stem == "years":
                year_col = next((i for i, field in enumerate(header) if field.startswith("year")), None)
                for row in rows:
                    if year_col is not None:
                        maps[stem][norm(row[year_col])].append(row[id_col])
            else:
                name_col = next((i for i, field in enumerate(header) if field == "name"), None)
                if name_col is not None:
                    for row in rows:
                        key = norm(row[name_col])
                        if key:
                            maps[stem][key].append(row[id_col])
    return maps, headers


def align_addition(
    base_zip: str | Path,
    addition_dir: str | Path,
    output_dir: str | Path,
) -> dict[str, Any]:
    base_zip = Path(base_zip).resolve()
    addition_dir = Path(addition_dir).resolve()
    output_dir = Path(output_dir).resolve()
    if not base_zip.is_file() or not addition_dir.is_dir():
        raise FileNotFoundError("baseline ZIP and addition directory must exist")
    if output_dir.exists():
        raise FileExistsError(output_dir)
    if (addition_dir / "paper_kg").is_dir():
        addition_dir = addition_dir / "paper_kg"
    base_maps, base_headers = _base_indexes(base_zip)
    raw_headers: dict[str, list[str]] = {}
    raw_rows: dict[str, list[list[str]]] = {}
    for stem in (*NODE_FILES, *RELATION_FILES):
        raw_headers[stem], raw_rows[stem] = _read_csv(addition_dir / f"{stem}.csv")

    id_maps: dict[str, dict[str, str]] = {stem: {} for stem in NODE_FILES}
    quarantined_papers: dict[str, dict[str, str]] = {}
    mapping_counts = Counter()
    paper_fields = {field: i for i, field in enumerate(raw_headers["papers"])}
    addition_title_counts = Counter(
        norm(row[paper_fields["title"]])
        for row in raw_rows["papers"]
        if norm(row[paper_fields["title"]])
    )
    for row in raw_rows["papers"]:
        source_id = row[_id_index(raw_headers["papers"])]
        title = norm(row[paper_fields.get("title", -1)])
        source_arxiv = row[paper_fields["arxiv_id"]] if "arxiv_id" in paper_fields else ""
        if suspect_modern_arxiv(source_arxiv):
            quarantined_papers[source_id] = {"reason": "suspect_arxiv_format", "title": title, "arxiv_id": source_arxiv}
            mapping_counts["paper_quarantined_suspect_arxiv"] += 1
            continue
        if title and addition_title_counts[title] > 1:
            quarantined_papers[source_id] = {"reason": "addition_title_collision", "title": title}
            mapping_counts["paper_quarantined_addition_title_collision"] += 1
            continue
        candidates: list[tuple[str, str]] = []
        for field, kind in (("arxiv_id", "arxiv"), ("doi", "doi")):
            value = arxiv(row[paper_fields[field]]) if kind == "arxiv" else doi(row[paper_fields[field]])
            if value:
                candidates.extend((kind, pid) for pid in base_maps["papers"].get(value, []))
        if candidates:
            unique = {pid for _, pid in candidates}
            if len(unique) == 1:
                id_maps["papers"][source_id] = next(iter(unique))
                mapping_counts["paper_exact_arxiv_or_doi"] += 1
                continue
            quarantined_papers[source_id] = {"reason": "ambiguous_exact_identity", "title": title}
            mapping_counts["paper_quarantined_ambiguous"] += 1
        elif title and len(base_maps["papers"].get(title, [])) == 1:
            quarantined_papers[source_id] = {"reason": "title_only_match", "title": title, "baseline_id": base_maps["papers"][title][0]}
            mapping_counts["paper_quarantined_title_only"] += 1
        else:
            mapping_counts["paper_new"] += 1

    for stem in NODE_FILES:
        if stem == "papers":
            continue
        id_col = _id_index(raw_headers[stem])
        name_col = next((i for i, field in enumerate(raw_headers[stem]) if field == "name"), None)
        value_col = next((i for i, field in enumerate(raw_headers[stem]) if field.startswith("year")), None)
        for row in raw_rows[stem]:
            source_id = row[id_col]
            key = norm(row[name_col]) if name_col is not None else norm(row[value_col]) if value_col is not None else ""
            candidates = base_maps[stem].get(key, []) if key else []
            if len(candidates) == 1:
                id_maps[stem][source_id] = candidates[0]
                mapping_counts[f"{stem}_aligned_by_name"] += 1
            elif len(candidates) > 1:
                mapping_counts[f"{stem}_ambiguous_kept_new"] += 1
            else:
                mapping_counts[f"{stem}_new"] += 1

    temp_root = Path(tempfile.mkdtemp(prefix=f".{output_dir.name}.tmp-", dir=output_dir.parent))
    try:
        paper_kg = temp_root / "paper_kg"
        paper_kg.mkdir(parents=True)
        kept_node_ids: dict[str, set[str]] = {stem: set() for stem in NODE_FILES}
        for stem in NODE_FILES:
            out_rows: list[list[str]] = []
            id_col = _id_index(raw_headers[stem])
            for row in raw_rows[stem]:
                source_id = row[id_col]
                if stem == "papers" and source_id in quarantined_papers:
                    continue
                if source_id in id_maps[stem]:
                    continue
                out_rows.append(row)
                kept_node_ids[stem].add(source_id)
            _write_csv(paper_kg / f"{stem}.csv", raw_headers[stem], out_rows)

        endpoint_types = {
            "authored_by": ("papers", "authors"), "published_in": ("papers", "venues"),
            "published_year": ("papers", "years"), "has_keyword": ("papers", "keywords"),
            "has_subject": ("papers", "subjects"), "cites": ("papers", "papers"),
        }
        relation_stats: dict[str, dict[str, int]] = {}
        for stem in RELATION_FILES:
            header = raw_headers[stem]
            start_col = next(i for i, field in enumerate(header) if field.startswith(":START_ID"))
            end_col = next(i for i, field in enumerate(header) if field.startswith(":END_ID"))
            start_type, end_type = endpoint_types[stem]
            out_rows = []
            skipped_quarantine = 0
            remapped = 0
            for row in raw_rows[stem]:
                source_start, source_end = row[start_col], row[end_col]
                if source_start in quarantined_papers or source_end in quarantined_papers:
                    skipped_quarantine += 1
                    continue
                new_start = id_maps[start_type].get(source_start, source_start)
                new_end = id_maps[end_type].get(source_end, source_end)
                if new_start != source_start or new_end != source_end:
                    remapped += 1
                row = list(row)
                row[start_col], row[end_col] = new_start, new_end
                out_rows.append(row)
            _write_csv(paper_kg / f"{stem}.csv", header, out_rows)
            relation_stats[stem] = {"input_rows": len(raw_rows[stem]), "output_rows": len(out_rows), "remapped_rows": remapped, "skipped_quarantined_rows": skipped_quarantine}

        report = {
            "schema": "shenzhi_neo4j_addition_alignment_v1",
            "base_zip": str(base_zip), "addition_dir": str(addition_dir),
            "mapping_counts": dict(sorted(mapping_counts.items())),
            "relation_stats": relation_stats,
            "quarantined_papers": quarantined_papers,
            "quality_gates": {
                "title_only_matches_not_auto_merged": True,
                "raw_inputs_modified": False,
                "exact_identity_mappings_only": True,
            },
        }
        (temp_root / "alignment_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        temp_root.replace(output_dir)
        return report
    except BaseException:
        shutil.rmtree(temp_root, ignore_errors=True)
        raise


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-zip", required=True, type=Path)
    parser.add_argument("--addition-dir", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    report = align_addition(args.base_zip, args.addition_dir, args.output_dir)
    print(json.dumps({"mapping_counts": report["mapping_counts"], "relation_stats": report["relation_stats"], "quarantined_papers": len(report["quarantined_papers"])}, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
