#!/bin/bash
set -euo pipefail

PROJECT_ROOT=${PROJECT_ROOT:-/data/home/scyb713/run/xzf/AAAI/autodl-tmp/clstr}
source "${PROJECT_ROOT}/scripts/sbatch/_clstr_gpu_env.sh"

DATA_ROOT=${DATA_ROOT:-data/clstr_unified_pretrain_v4_2_progressive_final_function_aug_v2}
OUTPUT_DIR=${OUTPUT_DIR:-outputs/clstr_unified_stage0_function_aug_v2_clean_calibration_smoke}
TOP_K=${TOP_K:-350}
MAX_STEPS=${MAX_STEPS:-1200}
LEARNING_RATE=${LEARNING_RATE:-2.0e-5}
RETRIEVAL_LOSS_MODE=${RETRIEVAL_LOSS_MODE:-multi_positive_nll}
SAMPLING_STRATEGY=${SAMPLING_STRATEGY:-handoff_balanced}
TEMPERED_CORRECTION_FRACTION=${TEMPERED_CORRECTION_FRACTION:-0.2}
EXPAND_ALIAS_POSITIVES=${EXPAND_ALIAS_POSITIVES:-1}

# Clean Stage0 calibration: frozen SkillRouter/text embeddings with a lightweight
# trainable calibration layer. Checkpoint warm-start is opt-in, not the default.
TRAIN_SKILL_EMBEDDINGS=${TRAIN_SKILL_EMBEDDINGS:-0}
TRAIN_ENCODER_PROJECTION=${TRAIN_ENCODER_PROJECTION:-0}
TRAIN_SKILL_ADAPTER=${TRAIN_SKILL_ADAPTER:-1}
TRAIN_RETRIEVAL_SCALE=${TRAIN_RETRIEVAL_SCALE:-1}
TRAIN_SKILL_BIAS=${TRAIN_SKILL_BIAS:-1}
INIT_CHECKPOINT_PATH=${INIT_CHECKPOINT_PATH:-}
INIT_CHECKPOINT_SKILLS_PATH=${INIT_CHECKPOINT_SKILLS_PATH:-}
PRESERVATION_ANCHOR_WEIGHT=${PRESERVATION_ANCHOR_WEIGHT:-0.0}

export DATA_ROOT OUTPUT_DIR TOP_K MAX_STEPS LEARNING_RATE
export RETRIEVAL_LOSS_MODE SAMPLING_STRATEGY TEMPERED_CORRECTION_FRACTION
export EXPAND_ALIAS_POSITIVES TRAIN_SKILL_EMBEDDINGS TRAIN_ENCODER_PROJECTION
export TRAIN_SKILL_ADAPTER TRAIN_RETRIEVAL_SCALE TRAIN_SKILL_BIAS
export INIT_CHECKPOINT_PATH INIT_CHECKPOINT_SKILLS_PATH PRESERVATION_ANCHOR_WEIGHT

exec bash scripts/sbatch/run_clstr_unified_stage0_biencoder_train.sh
