#!/bin/bash
set -euo pipefail

PROJECT_ROOT=${PROJECT_ROOT:-/data/home/scyb713/run/xzf/AAAI/autodl-tmp/clstr}
source "${PROJECT_ROOT}/scripts/sbatch/_clstr_gpu_env.sh"

DATA_ROOT=${DATA_ROOT:-data/clstr_unified_pretrain_v4_2_alfworld_hf_quality_nowweak}
OUTPUT_DIR=${OUTPUT_DIR:-outputs/clstr_unified_stage0_v4_2_nowweak_handoff_balanced_mpn_freezeE}
TOP_K=${TOP_K:-350}
RETRIEVAL_LOSS_MODE=${RETRIEVAL_LOSS_MODE:-multi_positive_nll}
SAMPLING_STRATEGY=${SAMPLING_STRATEGY:-handoff_balanced}
EXPAND_ALIAS_POSITIVES=${EXPAND_ALIAS_POSITIVES:-1}
TRAIN_SKILL_EMBEDDINGS=${TRAIN_SKILL_EMBEDDINGS:-0}
TRAIN_SKILL_BIAS=${TRAIN_SKILL_BIAS:-0}
TRAIN_ENCODER_PROJECTION=${TRAIN_ENCODER_PROJECTION:-0}
TRAIN_SKILL_ADAPTER=${TRAIN_SKILL_ADAPTER:-1}
TRAIN_RETRIEVAL_SCALE=${TRAIN_RETRIEVAL_SCALE:-1}

export DATA_ROOT OUTPUT_DIR TOP_K RETRIEVAL_LOSS_MODE SAMPLING_STRATEGY
export EXPAND_ALIAS_POSITIVES TRAIN_SKILL_EMBEDDINGS TRAIN_SKILL_BIAS
export TRAIN_ENCODER_PROJECTION TRAIN_SKILL_ADAPTER TRAIN_RETRIEVAL_SCALE

exec bash scripts/sbatch/run_clstr_unified_stage0_biencoder_train.sh
