#!/bin/bash
#SBATCH --time=06:00:00
set -euo pipefail

PROJECT_ROOT=${PROJECT_ROOT:-/data/home/scyb713/run/xzf/AAAI/autodl-tmp/clstr}
source "${PROJECT_ROOT}/scripts/sbatch/_clstr_gpu_env.sh"

TRAIN_PATH=${TRAIN_PATH:-data/clstr_unified_pretrain_v4_2_progressive_final/trajectories.jsonl}
SKILLS_PATH=${SKILLS_PATH:-data/clstr_unified_pretrain_v4_2_progressive_final/skill_pool.jsonl}
OUTPUT_DIR=${OUTPUT_DIR:-outputs/clstr_unified_stage1_v4_2_progressive_final_top350_inventory64_listwise_heads_init}
ROUTING_CHECKPOINT_PATH=${ROUTING_CHECKPOINT_PATH:-outputs/clstr_unified_stage0_v4_2_nowweak_handoff_balanced_mpn_freezeE/checkpoints/clstr_unified_retrieval_v2-step5000.pt}
STAGE0_TOP_M=${STAGE0_TOP_M:-350}
POLICY_LOSS_WEIGHT=${POLICY_LOSS_WEIGHT:-0.7}
TRANSITION_LOSS_WEIGHT=${TRANSITION_LOSS_WEIGHT:-0.2}
TRANSITION_SKILL_CE_LOSS_WEIGHT=${TRANSITION_SKILL_CE_LOSS_WEIGHT:-0.5}
TRANSITION_HARD_NEGATIVE_MARGIN_LOSS_WEIGHT=${TRANSITION_HARD_NEGATIVE_MARGIN_LOSS_WEIGHT:-0.0}
TRANSITION_HARD_NEGATIVE_MARGIN=${TRANSITION_HARD_NEGATIVE_MARGIN:-1.0}
BELIEF_LOSS_WEIGHT=${BELIEF_LOSS_WEIGHT:-0.1}
STOP_LOSS_WEIGHT=${STOP_LOSS_WEIGHT:-0.1}
RETRIEVAL_LOSS_WEIGHT=${RETRIEVAL_LOSS_WEIGHT:-0.0}
TRANSITION_INVENTORY_MASK_MODE=${TRANSITION_INVENTORY_MASK_MODE:-auto}
TRANSITION_INVENTORY_MIN_CANDIDATES=${TRANSITION_INVENTORY_MIN_CANDIDATES:-64}
TRANSITION_LOSS_TYPE=${TRANSITION_LOSS_TYPE:-listwise_nll}
TRANSITION_POSITIVE_MODE=${TRANSITION_POSITIVE_MODE:-gold_plus_equivalent}
TRANSITION_RESIDUAL_LAMBDA=${TRANSITION_RESIDUAL_LAMBDA:-0.25}
BENCHMARK_CAPS=${BENCHMARK_CAPS:-toolbench_g3=-1:traject_bench=-1:alfworld=-1:webshop=-1}
SAMPLING_STRATEGY=${SAMPLING_STRATEGY:-balanced_random}

export TRAIN_PATH SKILLS_PATH OUTPUT_DIR ROUTING_CHECKPOINT_PATH STAGE0_TOP_M
export POLICY_LOSS_WEIGHT TRANSITION_LOSS_WEIGHT TRANSITION_SKILL_CE_LOSS_WEIGHT
export TRANSITION_HARD_NEGATIVE_MARGIN_LOSS_WEIGHT TRANSITION_HARD_NEGATIVE_MARGIN
export BELIEF_LOSS_WEIGHT STOP_LOSS_WEIGHT RETRIEVAL_LOSS_WEIGHT
export TRANSITION_INVENTORY_MASK_MODE TRANSITION_INVENTORY_MIN_CANDIDATES
export TRANSITION_LOSS_TYPE TRANSITION_POSITIVE_MODE TRANSITION_RESIDUAL_LAMBDA
export BENCHMARK_CAPS SAMPLING_STRATEGY

exec bash scripts/sbatch/run_clstr_unified_stage1_heads_init.sh
