#!/bin/bash
#SBATCH --time=06:00:00
set -euo pipefail

PROJECT_ROOT=${PROJECT_ROOT:-/data/home/scyb713/run/xzf/AAAI/autodl-tmp/clstr}
source "${PROJECT_ROOT}/scripts/sbatch/_clstr_gpu_env.sh"

TRAJECTORIES_PATH=${TRAJECTORIES_PATH:-data/clstr_unified_pretrain_v4_2_progressive_final/trajectories.jsonl}
SKILLS_PATH=${SKILLS_PATH:-data/clstr_unified_pretrain_v4_2_progressive_final/skill_pool.jsonl}
OUTPUT_DIR=${OUTPUT_DIR:-outputs/clstr_unified_stage4_v4_2_progressive_final_prior_residual_l025_joint_act}
ROUTING_CHECKPOINT_PATH=${ROUTING_CHECKPOINT_PATH:-outputs/clstr_unified_stage0_v4_2_nowweak_handoff_balanced_mpn_freezeE/checkpoints/clstr_unified_retrieval_v2-step5000.pt}
HEAD_CHECKPOINT_PATH=${HEAD_CHECKPOINT_PATH:-outputs/clstr_unified_stage2_v4_2_progressive_final_top350_inventory64_listwise_rankprior_l025/checkpoints/clstr_full_base-step10000.pt}
MAX_STEPS=${MAX_STEPS:-2000}
BATCH_SIZE=${BATCH_SIZE:-8}
LEARNING_RATE=${LEARNING_RATE:-1.0e-4}
SEED=${SEED:-17}
CANDIDATE_COUNT=${CANDIDATE_COUNT:-64}
STAGE0_TOP_M=${STAGE0_TOP_M:-350}
STAGE0_INVENTORY_MIN_CANDIDATES=${STAGE0_INVENTORY_MIN_CANDIDATES:-64}
STAGE0_POSITIVE_MISSING_POLICY=${STAGE0_POSITIVE_MISSING_POLICY:-skip}
STAGE0_HANDOFF_QUERY_MODE=${STAGE0_HANDOFF_QUERY_MODE:-skillrouter_state}
STAGE0_HANDOFF_SAMPLE_MULTIPLIER=${STAGE0_HANDOFF_SAMPLE_MULTIPLIER:-8}
STAGE0_CANDIDATE_ENCODE_BATCH_SIZE=${STAGE0_CANDIDATE_ENCODE_BATCH_SIZE:-8}
STAGE0_CANDIDATE_PROGRESS_INTERVAL_BATCHES=${STAGE0_CANDIDATE_PROGRESS_INTERVAL_BATCHES:-100}
MAX_ROWS=${MAX_ROWS:-}
TRANSITION_RESIDUAL_LAMBDA=${TRANSITION_RESIDUAL_LAMBDA:-0.25}
TRANSITION_SCORING_MODE=${TRANSITION_SCORING_MODE:-stage0_rank_prior_plus_transition_residual}
TRAIN_TRANSITION=${TRAIN_TRANSITION:-1}
ALLOWED_BENCHMARKS=${ALLOWED_BENCHMARKS:-toolbench_g3,traject_bench,alfworld,webshop}

export TRAJECTORIES_PATH SKILLS_PATH OUTPUT_DIR ROUTING_CHECKPOINT_PATH HEAD_CHECKPOINT_PATH
export MAX_STEPS BATCH_SIZE LEARNING_RATE SEED CANDIDATE_COUNT MAX_ROWS
export STAGE0_TOP_M STAGE0_INVENTORY_MIN_CANDIDATES STAGE0_POSITIVE_MISSING_POLICY STAGE0_HANDOFF_QUERY_MODE
export STAGE0_HANDOFF_SAMPLE_MULTIPLIER STAGE0_CANDIDATE_ENCODE_BATCH_SIZE
export STAGE0_CANDIDATE_PROGRESS_INTERVAL_BATCHES
export TRANSITION_RESIDUAL_LAMBDA TRANSITION_SCORING_MODE TRAIN_TRANSITION
export ALLOWED_BENCHMARKS

exec bash scripts/sbatch/run_clstr_unified_stage4_act_train.sh
