#!/bin/bash
#SBATCH --time=04:00:00
set -euo pipefail

PROJECT_ROOT=${PROJECT_ROOT:-/data/home/scyb713/run/xzf/AAAI/autodl-tmp/clstr}
source "${PROJECT_ROOT}/scripts/sbatch/_clstr_gpu_env.sh"

export TRAIN_PATH=${TRAIN_PATH:-data/clstr_appworld_current_route_v1/trajectories.jsonl}
export SKILLS_PATH=${SKILLS_PATH:-data/clstr_appworld_current_route_v1/skill_pool.jsonl}
export OUTPUT_DIR=${OUTPUT_DIR:-outputs/clstr_appworld_current_stage1_heads_init}
export ROUTING_CHECKPOINT_PATH=${ROUTING_CHECKPOINT_PATH:-outputs/clstr_appworld_current_stage0_biencoder/checkpoints/clstr_unified_retrieval_v2-step2000.pt}
export STAGE0_TOP_M=${STAGE0_TOP_M:-100}
export STAGE0_POSITIVE_MISSING_POLICY=${STAGE0_POSITIVE_MISSING_POLICY:-skip}
export STAGE0_HANDOFF_SAMPLE_MULTIPLIER=${STAGE0_HANDOFF_SAMPLE_MULTIPLIER:-4}
export STAGE0_CANDIDATE_ENCODE_BATCH_SIZE=${STAGE0_CANDIDATE_ENCODE_BATCH_SIZE:-16}
export STAGE0_CANDIDATE_PROGRESS_INTERVAL_BATCHES=${STAGE0_CANDIDATE_PROGRESS_INTERVAL_BATCHES:-50}
export MAX_STEPS=${MAX_STEPS:-2000}
export BATCH_SIZE=${BATCH_SIZE:-4}
export LEARNING_RATE=${LEARNING_RATE:-1.0e-4}
export POLICY_LOSS_WEIGHT=${POLICY_LOSS_WEIGHT:-0.7}
export TRANSITION_LOSS_WEIGHT=${TRANSITION_LOSS_WEIGHT:-0.2}
export TRANSITION_SKILL_CE_LOSS_WEIGHT=${TRANSITION_SKILL_CE_LOSS_WEIGHT:-0.5}
export TRANSITION_HARD_NEGATIVE_MARGIN_LOSS_WEIGHT=${TRANSITION_HARD_NEGATIVE_MARGIN_LOSS_WEIGHT:-0.1}
export TRANSITION_HARD_NEGATIVE_MARGIN=${TRANSITION_HARD_NEGATIVE_MARGIN:-1.0}
export BELIEF_LOSS_WEIGHT=${BELIEF_LOSS_WEIGHT:-0.1}
export STOP_LOSS_WEIGHT=${STOP_LOSS_WEIGHT:-0.1}
export RETRIEVAL_LOSS_WEIGHT=${RETRIEVAL_LOSS_WEIGHT:-0.0}
export TRANSITION_INVENTORY_MASK_MODE=${TRANSITION_INVENTORY_MASK_MODE:-off}
export TRANSITION_INVENTORY_MIN_CANDIDATES=${TRANSITION_INVENTORY_MIN_CANDIDATES:-0}
export TRANSITION_LOSS_TYPE=${TRANSITION_LOSS_TYPE:-listwise_nll}
export TRANSITION_POSITIVE_MODE=${TRANSITION_POSITIVE_MODE:-gold_plus_equivalent}
export TRANSITION_RESIDUAL_LAMBDA=${TRANSITION_RESIDUAL_LAMBDA:-0.25}
export TRANSITION_SCORING_MODE=${TRANSITION_SCORING_MODE:-skill_prior_plus_action_observation_residual}
export ALLOWED_BENCHMARKS=${ALLOWED_BENCHMARKS:-appworld}
export BENCHMARK_CAPS=${BENCHMARK_CAPS:-appworld=-1}
export SAMPLING_STRATEGY=${SAMPLING_STRATEGY:-balanced_random}

exec bash scripts/sbatch/run_clstr_unified_stage1_heads_init.sh
